/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Annotate */

#ifndef _Included_Annotate
#define _Included_Annotate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Annotate
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Annotate_init
  (JNIEnv *, jclass);

/*
 * Class:     Annotate
 * Method:    startTask
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Annotate_startTask
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     Annotate
 * Method:    endTask
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Annotate_endTask
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     Annotate
 * Method:    setPathID
 * Signature: (Ljava/lang/String;I[B)V
 */
JNIEXPORT void JNICALL Java_Annotate_setPathID
  (JNIEnv *, jclass, jstring, jint, jbyteArray);

/*
 * Class:     Annotate
 * Method:    getPathID
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_Annotate_getPathID
  (JNIEnv *, jclass);

/*
 * Class:     Annotate
 * Method:    endPathID
 * Signature: (Ljava/lang/String;I[B)V
 */
JNIEXPORT void JNICALL Java_Annotate_endPathID
  (JNIEnv *, jclass, jstring, jint, jbyteArray);

/*
 * Class:     Annotate
 * Method:    notice
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Annotate_notice
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     Annotate
 * Method:    send
 * Signature: (Ljava/lang/String;I[BI)V
 */
JNIEXPORT void JNICALL Java_Annotate_send
  (JNIEnv *, jclass, jstring, jint, jbyteArray, jint);

/*
 * Class:     Annotate
 * Method:    receive
 * Signature: (Ljava/lang/String;I[BI)V
 */
JNIEXPORT void JNICALL Java_Annotate_receive
  (JNIEnv *, jclass, jstring, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
