/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Annotate */

#ifndef _Included_Annotate
#define _Included_Annotate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Annotate
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Annotate_init
  (JNIEnv *, jclass);

/*
 * Class:     Annotate
 * Method:    startTask
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Annotate_startTask
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Annotate
 * Method:    endTask
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Annotate_endTask
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Annotate
 * Method:    setPathID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Annotate_setPathID
  (JNIEnv *, jclass, jint);

/*
 * Class:     Annotate
 * Method:    endPathID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Annotate_endPathID
  (JNIEnv *, jclass, jint);

/*
 * Class:     Annotate
 * Method:    notice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Annotate_notice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Annotate
 * Method:    send
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Annotate_send
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Annotate
 * Method:    receive
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Annotate_receive
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
