#!/usr/bin/perl

use DBI;

$db = "anno";
$pat = shift;

$dbh = DBI->connect("DBI:mysql:$db", "root", "");
$query = $dbh->prepare("show tables");
$query->execute();
while (($t) = $query->fetchrow()) {
	if (!$pat || $t =~ /$pat/) {
		print "Dropping table \"$t\"\n";
		$dbh->prepare("drop table $t")->execute();
	}
}
